services:
  database:
    image: 'postgres:16.11-alpine3.23'
    environment:
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'local_password'
      POSTGRES_DB: 'mydatabase'
    ports:
      - '5432:5432'
